### ISSUE TITLE
Support Null Safety

### ISSUE THREAD

**Issue by devmgs** [oohyugi/sms_otp_auto_verify#16]
Thanks for this awesome plugin. Any plans for Null Safety for this package?

**Comment by excode** [comment]
Hi We are using your plugins sms_otp_auto_verify 1.2.2 

But there is no update for null safety. 
Are you going to upload the null safety version ? 
Please let us know. 
Thank you for the awesome plugins.

**Comment by komkumar** [comment]
when is the plan to upgrade this package to null Safety version??

**Comment by devmgs** [comment]
This project was last update on March 2020. I hope everyone is well on this project. Let's hope to hear from someone. WE can look at https://pub.dev/packages/android_sms_retriever. I will try to use this plugin as it seems as an alternative with null safety.

**Comment by oohyugi** [comment]
please update version to 2.0.0 thank you
