### ISSUE TITLE
Android V2 embedding

### ISSUE THREAD

**Issue by rsree1210** [oohyugi/sms_otp_auto_verify#19]
This package isn't compatible with Flutter 2.5. Getting the following error:

The plugin `sms_otp_auto_verify` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

Please let us know if there is any plan to update this package in the near soon?

**Comment by Ajaydey1903** [comment]
i am also getting same error can anyone help me to resolve it.

**Comment by oohyugi** [comment]
updated, please migrate to version 2.0.0
